AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.8
    Tracing: Active
Resources:
  ClustersDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: N
        - AttributeName: hypervisors
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
        - AttributeType: customer_domain
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
  HypervisorsDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: status
          AttributeType: N
        - AttributeName: cluster_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
        - AttributeType: customer_domain
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
        - AttributeName: cluster_id
          KeyType: RANGE