version: 2.1

DEPLOY_JOB_DEFAULTS: &DEPLOY_JOB_DEFAULTS
  docker:
    - image: ryandub/xplat-ci-images:latest
  environment:
    AWS_PROFILE: vdo-rpcv-dev
  working_directory: ~/vdo-rpcv
orbs:
  aws-cli: circleci/aws-cli@0.1.13
commands:
  build_prep:
    description: "Set up auth and S3"
    parameters:
      stage:
        type: string
    steps:
    executor: aws-cli/default
    environment:
      AWS_REGION: us-west-2
    steps:
      - aws-cli/install
      - aws-cli/configure:
          profile-name: vdo-rpcv-<< parameters.stage >>
          aws-access-key-id: AWS_ACCESS_KEY_ID_<< parameters.stage >>
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_<< parameters.stage >>
          aws-region: AWS_REGION
      - run: aws --profile vdo-rpcv-<< parameters.stage >> s3api head-bucket --bucket "vdo-rpcv-<< parameters.stage >>" >/dev/null 2>&1 ||  aws --profile vdo-rpcv-<< parameters.stage >> s3 mb s3://"vdo-rpcv-<< parameters.stage >>" --region us-west-2
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - "*"
workflows:
  release:
    jobs:
      - build_prep