version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
commands:
  build_prep:
    description: "Set up auth and S3 for stage: << parameters.stage >>"
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          profile-name: vdo-rpcv-<< parameters.stage >>
          aws-access-key-id: AWS_ACCESS_KEY_ID_<< parameters.stage >>
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_<< parameters.stage >>
      - run: aws --profile vdo-rpcv-<< parameters.stage >> s3api head-bucket --bucket "vdo-rpcv-<< parameters.stage >>" >/dev/null 2>&1 ||  aws --profile vdo-rpcv-<< parameters.stage >> s3 mb s3://"vdo-rpcv-<< parameters.stage >>" --region us-west-2
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - "*"
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry deps
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
  gate_test:
    description: All the tests!
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Run gate tests
          command: |
            poetry run doit -n 4 -f ./tests/gate_tests.py
  sam_build:
    description: Build app for stage << parameters.stage >>
    parameters:
      stage:
        type: string
    steps:
      - attach_workspace:
          at: ~/.aws
      - checkout
      - run:
          name: Build sam app
          command: |
            sam build --profile vdo-rpcv-<< parameters.stage >> --region ${AWS_DEFAULT_REGION} -t ./template.yaml
  sam_deploy:
    description: Deploy rpcv- for stage << parameters.stage >>
    parameters:
      stage:
        type: string
    steps:
      - attach_workspace:
          at: ~/.aws
      - checkout
      - run:
          name: Deploy app
          command: |
            sam deploy \
            --stack-name rpcv-api-<< parameters.stage >> \
            --s3-prefix << parameters.stage >> \
            --s3-bucket vdo-rpcv-<< parameters.stage >> \
            --profile vdo-rpcv-<< parameters.stage >> \
            --region ${AWS_DEFAULT_REGION} \
            --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM \
            --parameter-overrides Stage=<< parameters.stage >> \
            --template ./template.yaml
jobs:
  gate_tests:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - gate_test
  dev_build_prep:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - build_prep:
          stage: dev
  dev_build:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - sam_build:
          stage: dev
  dev_deploy:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - sam_deploy:
          stage: dev
workflows:
  release:
    jobs:
      - dev_build_prep
      - dev_build:
          requires:
            - dev_build_prep
      - gate_tests:
          requires:
            - dev_build_prep
      - dev_deploy:
          requires:
            - gate_tests
            - dev_build
