version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
commands:
  build_prep:
    description: "Set up auth and S3 for stage: << parameters.stage >>"
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          profile-name: vdo-rpcv-<< parameters.stage >>
          aws-access-key-id: AWS_ACCESS_KEY_ID_<< parameters.stage >>
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_<< parameters.stage >>
      - run: aws --profile vdo-rpcv-<< parameters.stage >> s3api head-bucket --bucket "vdo-rpcv-<< parameters.stage >>" >/dev/null 2>&1 ||  aws --profile vdo-rpcv-<< parameters.stage >> s3 mb s3://"vdo-rpcv-<< parameters.stage >>" --region us-west-2
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - "*"
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry deps
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
  unit-test:
    description: All the tests!
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
            - tox-{{ checksum "tox.ini" }}
      - run:
          name: Run gate tests
          command: |
            poetry run tox
      - save_cache:
          key: tox-{{ checksum "tox.ini" }}
          paths:
            - ~/.tox
  build:
    description: Build app for stage << parameters.stage >>
    parameters:
      stage:
        type: string
    steps:
      - attach_workspace:
          at: ~/.aws
      - checkout
      - run:
          name: Build sam app
          command: |
            sam build --profile vdo-rpcv-<< parameters.stage >> --region ${AWS_DEFAULT_REGION} -t ./template.yaml
jobs:
  unit_tests:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - unit-test
  dev_build_prep:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - build_prep:
          stage: dev
  dev_build:
    docker:
      - image: chalupaul/sambuild:latest
    steps:
      - build:
          stage: dev
workflows:
  release:
    jobs:
      - dev_build_prep
      - dev_build:
          requires:
            - dev_build_prep
      - unit_tests:
          requires:
            - dev_build_prep
