version: 2.1

DEPLOY_JOB_DEFAULTS: &DEPLOY_JOB_DEFAULTS
  docker:
    - image: ryandub/xplat-ci-images:latest
  environment:
    AWS_PROFILE: vdo-rpcv-dev
  working_directory: ~/vdo-rpcv
orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-serverless: circleci/aws-serverless@1.0.2
commands:
  prep-s3:
    description: "Ensures s3 buckets exist"
    parameters:
      stage:
        type: string
    steps:
      - run: aws --profile vdo-rpcv-<< parameters.stage >> s3api head-bucket --bucket "vdo-rpcv-<< parameters.stage >>" >/dev/null 2>&1 ||  aws --profile vdo-rpcv-<< parameters.stage >> s3 mb s3://"vdo-rpcv-<< parameters.stage >>" --region us-west-2
workflows:
  release:
    jobs:
      - aws-serverless/deploy:
          name: deploy-dev
          aws-access-key-id: AWS_ACCESS_KEY_ID_DEV
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_DEV
          aws-region: AWS_REGION_DEV
          profile-name: vdo-rpcv-dev
          s3-bucket: vdo-rpcv-dev
          template: ./template.yaml
          stack-name: rpcv-api
