version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
executors:
  sam_build:
    docker:
      - image: chalupaul/sambuild:latest
commands:
  build_prep:
    description: "Set up auth and S3 for stage: << parameters.stage >>"
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Set region variable
          command: export AWS_REGION=us-west-2
      - aws-cli/setup:
          profile-name: vdo-rpcv-<< parameters.stage >>
          aws-access-key-id: AWS_ACCESS_KEY_ID_<< parameters.stage >>
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_<< parameters.stage >>
          aws-region: AWS_REGION
      - run:
          name: Ensule S3 bucket
          command: |
            aws s3api head-bucket \
            --profile vdo-rpcv-<< parameters.stage >> \
            --bucket "vdo-rpcv-<< parameters.stage >>" >/dev/null 2>&1 \
            || aws s3 mb \
            --profile vdo-rpcv-<< parameters.stage >> \
            --region us-west-2 \
            s3://"vdo-rpcv-<< parameters.stage >>"
      - persist_to_workspace:
          root: ~/.aws
          paths:
            - "*"
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: install poetry deps
          command: |
            poetry install
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
  gate_test:
    description: All the tests!
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - run:
          name: Run gate tests
          command: |
            poetry run doit -n 4 -f ./gate_tests.py
      - run:
          name: Run unit tests
          command: |
            poetry run pytest --cov=rpcv ./rpcv/tests
  sam_build:
    description: Build app for stage << parameters.stage >>
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - attach_workspace:
          at: ~/.aws
      - run:
          name: Validate sam app
          command: |
            sam validate \
            --profile "vdo-rpcv-<< parameters.stage >>" \
            --region us-west-2 \
            --template ./template.yaml
      - run:
          name: Build requirements.txt
          command: |
            pip  freeze | grep -v rpcv.git > ./rpcv/api/requirements.txt
      - run:
          name: Build sam app
          command: |
            sam build \
            --profile vdo-rpcv-<< parameters.stage >> \
            --region us-west-2 \
            --template ./template.yaml
  sam_deploy:
    description: Deploy rpcv for stage << parameters.stage >>
    parameters:
      stage:
        type: string
    steps:
      - attach_workspace:
          at: ~/.aws
      - checkout
      - run:
          name: Deploy app
          command: |
            sam deploy \
            --stack-name rpcv-api-<< parameters.stage >> \
            --s3-prefix << parameters.stage >> \
            --s3-bucket vdo-rpcv-<< parameters.stage >> \
            --profile vdo-rpcv-<< parameters.stage >> \
            --region us-west-2 \
            --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM CAPABILITY_IAM \
            --parameter-overrides Stage=<< parameters.stage >> \
            --no-fail-on-empty-changeset \
            --template ./template.yaml
jobs:
  gate_tests:
    executor: sam_build
    steps:
      - gate_test
  dev_build_prep:
    executor: sam_build
    steps:
      - build_prep:
          stage: dev
  dev_build:
    executor: sam_build
    steps:
      - sam_build:
          stage: dev
  dev_deploy:
    executor: sam_build
    steps:
      - sam_deploy:
          stage: dev
workflows:
  release:dev:
    jobs:
      - dev_build_prep
      - dev_build:
          requires:
            - dev_build_prep
      - gate_tests:
          requires:
            - dev_build_prep
      - dev_deploy:
          requires:
            - gate_tests
            - dev_build
